### ISSUE TITLE
How to specify the unquoted function to downloadFile? 

### ISSUE THREAD

**Issue by guodudou2** [cb4ds/periscope#66]
Hello,

I am trying to use downloadFile Shiny Module from your package as following:

UI side:

download_info_box <- box(
                                           title = "Step 2: Download template sample sheet.",
                                           status = "primary",
                                           solidHeader = TRUE, width = 12,

                                           fluidRow(
                                                           column(3, h4(icon_skip_check("download"), "Download")),
                                                           column(2, offset = 7, help_button("download_info"))
                                                          ),
                      
                                          fluidRow(
                                                        column(4, periscope::downloadFileButton(id = "DownloadInfo", 
                                                                                                                           downloadtypes = c("xlsx"), 
                                                                                                                           hovertext = "Click to download"
                                                                                                                        )
                              )
                       )
                     )

Server side:

master <- reactiveFileReader(500, session, filePath = file.path(data_dir, "Master_Dataset_Sheet.xlsx"),  
                             readFunc = read_xlsx, 
                             col_types = c("numeric", rep("text", 15))
                             )

periscope::downloadFile(id="DownloadInfo",
                                        logger = ss_userAction.Log,
                                       filenameroot = "mydownload1",
                                       datafxns = list(xlsx = mydatafxn1),
                                      aspectratio = 1
                                     )

I couldn't get it to work. I think it is due to the "datafxns" part in server side function. In your document https://cran.r-project.org/web/packages/periscope/vignettes/downloadFile-module.html , it only says an unquoted function. I am wondering how to generate this type function to just download "master()"?

Thank you very much,
Wendy

**Comment by cb4ds** [comment]
Hi, you'll create a function or reactive (which is a special type of function) that is called by the module to get the data.  So in your example above you'll have a function (or reactive) called "mydatafxn1" that returns the file you want to allow the user to download - in xlsx format as you've listed above.

```
mydatafxn1 <- function() {
get.xlsx('myfile.xlsx')
}

# or alternatively

mydatafxn1 <- reactive({
read.xlsx('myfile.xlsx')
}
```

This is just a regular (no argument) function that gets called by the application at the appropriate time.  You send in the name "unquoted" - you do not want to call it with quotes around it (that's a character string) but nothing else special is required other than that the function (if regular) can't take any parameters.

Hope this helps!  If you create a sample app the same paradigm is used for downloadableTable modules, and there is an example where a function is used to return a table of data that is used for display/download by that module:

```
create_new_application('mysampleapp', location = '.', sampleapp = TRUE)
```
